// Code generated by mockery v1.0.1. DO NOT EDIT.

package mocks

import (
	context "context"

	admin "github.com/flyteorg/flyteidl/gen/pb-go/flyteidl/admin"

	mock "github.com/stretchr/testify/mock"
)

// MetricsInterface is an autogenerated mock type for the MetricsInterface type
type MetricsInterface struct {
	mock.Mock
}

type MetricsInterface_GetExecutionMetrics struct {
	*mock.Call
}

func (_m MetricsInterface_GetExecutionMetrics) Return(_a0 *admin.WorkflowExecutionGetMetricsResponse, _a1 error) *MetricsInterface_GetExecutionMetrics {
	return &MetricsInterface_GetExecutionMetrics{Call: _m.Call.Return(_a0, _a1)}
}

func (_m *MetricsInterface) OnGetExecutionMetrics(ctx context.Context, request admin.WorkflowExecutionGetMetricsRequest) *MetricsInterface_GetExecutionMetrics {
	c_call := _m.On("GetExecutionMetrics", ctx, request)
	return &MetricsInterface_GetExecutionMetrics{Call: c_call}
}

func (_m *MetricsInterface) OnGetExecutionMetricsMatch(matchers ...interface{}) *MetricsInterface_GetExecutionMetrics {
	c_call := _m.On("GetExecutionMetrics", matchers...)
	return &MetricsInterface_GetExecutionMetrics{Call: c_call}
}

// GetExecutionMetrics provides a mock function with given fields: ctx, request
func (_m *MetricsInterface) GetExecutionMetrics(ctx context.Context, request admin.WorkflowExecutionGetMetricsRequest) (*admin.WorkflowExecutionGetMetricsResponse, error) {
	ret := _m.Called(ctx, request)

	var r0 *admin.WorkflowExecutionGetMetricsResponse
	if rf, ok := ret.Get(0).(func(context.Context, admin.WorkflowExecutionGetMetricsRequest) *admin.WorkflowExecutionGetMetricsResponse); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.WorkflowExecutionGetMetricsResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, admin.WorkflowExecutionGetMetricsRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type MetricsInterface_GetTaskMetrics struct {
	*mock.Call
}

func (_m MetricsInterface_GetTaskMetrics) Return(_a0 *admin.GetTaskMetricsRequest, _a1 error) *MetricsInterface_GetTaskMetrics {
	return &MetricsInterface_GetTaskMetrics{Call: _m.Call.Return(_a0, _a1)}
}

func (_m *MetricsInterface) OnGetTaskMetrics(ctx context.Context, request admin.GetTaskMetricsRequest) *MetricsInterface_GetTaskMetrics {
	c_call := _m.On("GetTaskMetrics", ctx, request)
	return &MetricsInterface_GetTaskMetrics{Call: c_call}
}

func (_m *MetricsInterface) OnGetTaskMetricsMatch(matchers ...interface{}) *MetricsInterface_GetTaskMetrics {
	c_call := _m.On("GetTaskMetrics", matchers...)
	return &MetricsInterface_GetTaskMetrics{Call: c_call}
}

// GetTaskMetrics provides a mock function with given fields: ctx, request
func (_m *MetricsInterface) GetTaskMetrics(ctx context.Context, request admin.GetTaskMetricsRequest) (*admin.GetTaskMetricsRequest, error) {
	ret := _m.Called(ctx, request)

	var r0 *admin.GetTaskMetricsRequest
	if rf, ok := ret.Get(0).(func(context.Context, admin.GetTaskMetricsRequest) *admin.GetTaskMetricsRequest); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.GetTaskMetricsRequest)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, admin.GetTaskMetricsRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
