// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots.

package config

import (
	"encoding/json"
	"fmt"
	"reflect"
	"strings"
	"testing"

	"github.com/mitchellh/mapstructure"
	"github.com/stretchr/testify/assert"
)

var dereferencableKindsServerConfig = map[reflect.Kind]struct{}{
	reflect.Array: {}, reflect.Chan: {}, reflect.Map: {}, reflect.Ptr: {}, reflect.Slice: {},
}

// Checks if t is a kind that can be dereferenced to get its underlying type.
func canGetElementServerConfig(t reflect.Kind) bool {
	_, exists := dereferencableKindsServerConfig[t]
	return exists
}

// This decoder hook tests types for json unmarshaling capability. If implemented, it uses json unmarshal to build the
// object. Otherwise, it'll just pass on the original data.
func jsonUnmarshalerHookServerConfig(_, to reflect.Type, data interface{}) (interface{}, error) {
	unmarshalerType := reflect.TypeOf((*json.Unmarshaler)(nil)).Elem()
	if to.Implements(unmarshalerType) || reflect.PtrTo(to).Implements(unmarshalerType) ||
		(canGetElementServerConfig(to.Kind()) && to.Elem().Implements(unmarshalerType)) {

		raw, err := json.Marshal(data)
		if err != nil {
			fmt.Printf("Failed to marshal Data: %v. Error: %v. Skipping jsonUnmarshalHook", data, err)
			return data, nil
		}

		res := reflect.New(to).Interface()
		err = json.Unmarshal(raw, &res)
		if err != nil {
			fmt.Printf("Failed to umarshal Data: %v. Error: %v. Skipping jsonUnmarshalHook", data, err)
			return data, nil
		}

		return res, nil
	}

	return data, nil
}

func decode_ServerConfig(input, result interface{}) error {
	config := &mapstructure.DecoderConfig{
		TagName:          "json",
		WeaklyTypedInput: true,
		Result:           result,
		DecodeHook: mapstructure.ComposeDecodeHookFunc(
			mapstructure.StringToTimeDurationHookFunc(),
			mapstructure.StringToSliceHookFunc(","),
			jsonUnmarshalerHookServerConfig,
		),
	}

	decoder, err := mapstructure.NewDecoder(config)
	if err != nil {
		return err
	}

	return decoder.Decode(input)
}

func join_ServerConfig(arr interface{}, sep string) string {
	listValue := reflect.ValueOf(arr)
	strs := make([]string, 0, listValue.Len())
	for i := 0; i < listValue.Len(); i++ {
		strs = append(strs, fmt.Sprintf("%v", listValue.Index(i)))
	}

	return strings.Join(strs, sep)
}

func testDecodeJson_ServerConfig(t *testing.T, val, result interface{}) {
	assert.NoError(t, decode_ServerConfig(val, result))
}

func testDecodeSlice_ServerConfig(t *testing.T, vStringSlice, result interface{}) {
	assert.NoError(t, decode_ServerConfig(vStringSlice, result))
}

func TestServerConfig_GetPFlagSet(t *testing.T) {
	val := ServerConfig{}
	cmdFlags := val.GetPFlagSet("")
	assert.True(t, cmdFlags.HasFlags())
}

func TestServerConfig_SetFlags(t *testing.T) {
	actual := ServerConfig{}
	cmdFlags := actual.GetPFlagSet("")
	assert.True(t, cmdFlags.HasFlags())

	t.Run("Test_httpPort", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vInt, err := cmdFlags.GetInt("httpPort"); err == nil {
				assert.Equal(t, int(defaultServerConfig.HTTPPort), vInt)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("httpPort", testValue)
			if vInt, err := cmdFlags.GetInt("httpPort"); err == nil {
				testDecodeJson_ServerConfig(t, fmt.Sprintf("%v", vInt), &actual.HTTPPort)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_grpcPort", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vInt, err := cmdFlags.GetInt("grpcPort"); err == nil {
				assert.Equal(t, int(defaultServerConfig.GrpcPort), vInt)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("grpcPort", testValue)
			if vInt, err := cmdFlags.GetInt("grpcPort"); err == nil {
				testDecodeJson_ServerConfig(t, fmt.Sprintf("%v", vInt), &actual.GrpcPort)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_grpcServerReflection", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vBool, err := cmdFlags.GetBool("grpcServerReflection"); err == nil {
				assert.Equal(t, bool(defaultServerConfig.GrpcServerReflection), vBool)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("grpcServerReflection", testValue)
			if vBool, err := cmdFlags.GetBool("grpcServerReflection"); err == nil {
				testDecodeJson_ServerConfig(t, fmt.Sprintf("%v", vBool), &actual.GrpcServerReflection)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_kube-config", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vString, err := cmdFlags.GetString("kube-config"); err == nil {
				assert.Equal(t, string(defaultServerConfig.KubeConfig), vString)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("kube-config", testValue)
			if vString, err := cmdFlags.GetString("kube-config"); err == nil {
				testDecodeJson_ServerConfig(t, fmt.Sprintf("%v", vString), &actual.KubeConfig)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_master", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vString, err := cmdFlags.GetString("master"); err == nil {
				assert.Equal(t, string(defaultServerConfig.Master), vString)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("master", testValue)
			if vString, err := cmdFlags.GetString("master"); err == nil {
				testDecodeJson_ServerConfig(t, fmt.Sprintf("%v", vString), &actual.Master)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_security.secure", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vBool, err := cmdFlags.GetBool("security.secure"); err == nil {
				assert.Equal(t, bool(defaultServerConfig.Security.Secure), vBool)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("security.secure", testValue)
			if vBool, err := cmdFlags.GetBool("security.secure"); err == nil {
				testDecodeJson_ServerConfig(t, fmt.Sprintf("%v", vBool), &actual.Security.Secure)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_security.ssl.certificateFile", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vString, err := cmdFlags.GetString("security.ssl.certificateFile"); err == nil {
				assert.Equal(t, string(defaultServerConfig.Security.Ssl.CertificateFile), vString)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("security.ssl.certificateFile", testValue)
			if vString, err := cmdFlags.GetString("security.ssl.certificateFile"); err == nil {
				testDecodeJson_ServerConfig(t, fmt.Sprintf("%v", vString), &actual.Security.Ssl.CertificateFile)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_security.ssl.keyFile", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vString, err := cmdFlags.GetString("security.ssl.keyFile"); err == nil {
				assert.Equal(t, string(defaultServerConfig.Security.Ssl.KeyFile), vString)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("security.ssl.keyFile", testValue)
			if vString, err := cmdFlags.GetString("security.ssl.keyFile"); err == nil {
				testDecodeJson_ServerConfig(t, fmt.Sprintf("%v", vString), &actual.Security.Ssl.KeyFile)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_security.useAuth", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vBool, err := cmdFlags.GetBool("security.useAuth"); err == nil {
				assert.Equal(t, bool(defaultServerConfig.Security.UseAuth), vBool)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("security.useAuth", testValue)
			if vBool, err := cmdFlags.GetBool("security.useAuth"); err == nil {
				testDecodeJson_ServerConfig(t, fmt.Sprintf("%v", vBool), &actual.Security.UseAuth)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_security.auth.httpAuthorizationHeader", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vString, err := cmdFlags.GetString("security.auth.httpAuthorizationHeader"); err == nil {
				assert.Equal(t, string(defaultServerConfig.Security.Auth.HTTPAuthorizationHeader), vString)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("security.auth.httpAuthorizationHeader", testValue)
			if vString, err := cmdFlags.GetString("security.auth.httpAuthorizationHeader"); err == nil {
				testDecodeJson_ServerConfig(t, fmt.Sprintf("%v", vString), &actual.Security.Auth.HTTPAuthorizationHeader)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_security.auth.grpcAuthorizationHeader", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vString, err := cmdFlags.GetString("security.auth.grpcAuthorizationHeader"); err == nil {
				assert.Equal(t, string(defaultServerConfig.Security.Auth.GrpcAuthorizationHeader), vString)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("security.auth.grpcAuthorizationHeader", testValue)
			if vString, err := cmdFlags.GetString("security.auth.grpcAuthorizationHeader"); err == nil {
				testDecodeJson_ServerConfig(t, fmt.Sprintf("%v", vString), &actual.Security.Auth.GrpcAuthorizationHeader)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_security.auth.disableForHttp", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vBool, err := cmdFlags.GetBool("security.auth.disableForHttp"); err == nil {
				assert.Equal(t, bool(defaultServerConfig.Security.Auth.DisableForHTTP), vBool)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("security.auth.disableForHttp", testValue)
			if vBool, err := cmdFlags.GetBool("security.auth.disableForHttp"); err == nil {
				testDecodeJson_ServerConfig(t, fmt.Sprintf("%v", vBool), &actual.Security.Auth.DisableForHTTP)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_security.auth.disableForGrpc", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vBool, err := cmdFlags.GetBool("security.auth.disableForGrpc"); err == nil {
				assert.Equal(t, bool(defaultServerConfig.Security.Auth.DisableForGrpc), vBool)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("security.auth.disableForGrpc", testValue)
			if vBool, err := cmdFlags.GetBool("security.auth.disableForGrpc"); err == nil {
				testDecodeJson_ServerConfig(t, fmt.Sprintf("%v", vBool), &actual.Security.Auth.DisableForGrpc)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_security.auth.userAuth.redirectUrl", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vString, err := cmdFlags.GetString("security.auth.userAuth.redirectUrl"); err == nil {
				assert.Equal(t, string(defaultServerConfig.Security.Auth.UserAuth.RedirectURL.String()), vString)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := defaultServerConfig.Security.Auth.UserAuth.RedirectURL.String()

			cmdFlags.Set("security.auth.userAuth.redirectUrl", testValue)
			if vString, err := cmdFlags.GetString("security.auth.userAuth.redirectUrl"); err == nil {
				testDecodeJson_ServerConfig(t, fmt.Sprintf("%v", vString), &actual.Security.Auth.UserAuth.RedirectURL)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_security.auth.userAuth.openId.clientId", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vString, err := cmdFlags.GetString("security.auth.userAuth.openId.clientId"); err == nil {
				assert.Equal(t, string(defaultServerConfig.Security.Auth.UserAuth.OpenID.ClientID), vString)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("security.auth.userAuth.openId.clientId", testValue)
			if vString, err := cmdFlags.GetString("security.auth.userAuth.openId.clientId"); err == nil {
				testDecodeJson_ServerConfig(t, fmt.Sprintf("%v", vString), &actual.Security.Auth.UserAuth.OpenID.ClientID)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_security.auth.userAuth.openId.clientSecretName", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vString, err := cmdFlags.GetString("security.auth.userAuth.openId.clientSecretName"); err == nil {
				assert.Equal(t, string(defaultServerConfig.Security.Auth.UserAuth.OpenID.ClientSecretName), vString)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("security.auth.userAuth.openId.clientSecretName", testValue)
			if vString, err := cmdFlags.GetString("security.auth.userAuth.openId.clientSecretName"); err == nil {
				testDecodeJson_ServerConfig(t, fmt.Sprintf("%v", vString), &actual.Security.Auth.UserAuth.OpenID.ClientSecretName)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_security.auth.userAuth.openId.clientSecretFile", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vString, err := cmdFlags.GetString("security.auth.userAuth.openId.clientSecretFile"); err == nil {
				assert.Equal(t, string(defaultServerConfig.Security.Auth.UserAuth.OpenID.DeprecatedClientSecretFile), vString)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("security.auth.userAuth.openId.clientSecretFile", testValue)
			if vString, err := cmdFlags.GetString("security.auth.userAuth.openId.clientSecretFile"); err == nil {
				testDecodeJson_ServerConfig(t, fmt.Sprintf("%v", vString), &actual.Security.Auth.UserAuth.OpenID.DeprecatedClientSecretFile)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_security.auth.userAuth.openId.baseUrl", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vString, err := cmdFlags.GetString("security.auth.userAuth.openId.baseUrl"); err == nil {
				assert.Equal(t, string(defaultServerConfig.Security.Auth.UserAuth.OpenID.BaseURL.String()), vString)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := defaultServerConfig.Security.Auth.UserAuth.OpenID.BaseURL.String()

			cmdFlags.Set("security.auth.userAuth.openId.baseUrl", testValue)
			if vString, err := cmdFlags.GetString("security.auth.userAuth.openId.baseUrl"); err == nil {
				testDecodeJson_ServerConfig(t, fmt.Sprintf("%v", vString), &actual.Security.Auth.UserAuth.OpenID.BaseURL)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_security.auth.userAuth.openId.callbackUrl", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vString, err := cmdFlags.GetString("security.auth.userAuth.openId.callbackUrl"); err == nil {
				assert.Equal(t, string(defaultServerConfig.Security.Auth.UserAuth.OpenID.CallbackURL.String()), vString)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := defaultServerConfig.Security.Auth.UserAuth.OpenID.CallbackURL.String()

			cmdFlags.Set("security.auth.userAuth.openId.callbackUrl", testValue)
			if vString, err := cmdFlags.GetString("security.auth.userAuth.openId.callbackUrl"); err == nil {
				testDecodeJson_ServerConfig(t, fmt.Sprintf("%v", vString), &actual.Security.Auth.UserAuth.OpenID.CallbackURL)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_security.auth.userAuth.openId.scopes", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vStringSlice, err := cmdFlags.GetStringSlice("security.auth.userAuth.openId.scopes"); err == nil {
				assert.Equal(t, []string([]string{}), vStringSlice)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := join_ServerConfig("1,1", ",")

			cmdFlags.Set("security.auth.userAuth.openId.scopes", testValue)
			if vStringSlice, err := cmdFlags.GetStringSlice("security.auth.userAuth.openId.scopes"); err == nil {
				testDecodeSlice_ServerConfig(t, join_ServerConfig(vStringSlice, ","), &actual.Security.Auth.UserAuth.OpenID.Scopes)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_security.auth.userAuth.openId.aud", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vStringSlice, err := cmdFlags.GetStringSlice("security.auth.userAuth.openId.aud"); err == nil {
				assert.Equal(t, []string([]string{}), vStringSlice)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := join_ServerConfig("1,1", ",")

			cmdFlags.Set("security.auth.userAuth.openId.aud", testValue)
			if vStringSlice, err := cmdFlags.GetStringSlice("security.auth.userAuth.openId.aud"); err == nil {
				testDecodeSlice_ServerConfig(t, join_ServerConfig(vStringSlice, ","), &actual.Security.Auth.UserAuth.OpenID.AcceptedAudiences)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_security.auth.userAuth.cookie_hash_key_secret_name", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vString, err := cmdFlags.GetString("security.auth.userAuth.cookie_hash_key_secret_name"); err == nil {
				assert.Equal(t, string(defaultServerConfig.Security.Auth.UserAuth.CookieHashKeySecretName), vString)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("security.auth.userAuth.cookie_hash_key_secret_name", testValue)
			if vString, err := cmdFlags.GetString("security.auth.userAuth.cookie_hash_key_secret_name"); err == nil {
				testDecodeJson_ServerConfig(t, fmt.Sprintf("%v", vString), &actual.Security.Auth.UserAuth.CookieHashKeySecretName)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_security.auth.userAuth.cookie_block_key_secret_name", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vString, err := cmdFlags.GetString("security.auth.userAuth.cookie_block_key_secret_name"); err == nil {
				assert.Equal(t, string(defaultServerConfig.Security.Auth.UserAuth.CookieBlockKeySecretName), vString)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("security.auth.userAuth.cookie_block_key_secret_name", testValue)
			if vString, err := cmdFlags.GetString("security.auth.userAuth.cookie_block_key_secret_name"); err == nil {
				testDecodeJson_ServerConfig(t, fmt.Sprintf("%v", vString), &actual.Security.Auth.UserAuth.CookieBlockKeySecretName)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_security.auth.appAuth.selfAuthServer.issuer", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vString, err := cmdFlags.GetString("security.auth.appAuth.selfAuthServer.issuer"); err == nil {
				assert.Equal(t, string(defaultServerConfig.Security.Auth.AppAuth.SelfAuthServer.Issuer), vString)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("security.auth.appAuth.selfAuthServer.issuer", testValue)
			if vString, err := cmdFlags.GetString("security.auth.appAuth.selfAuthServer.issuer"); err == nil {
				testDecodeJson_ServerConfig(t, fmt.Sprintf("%v", vString), &actual.Security.Auth.AppAuth.SelfAuthServer.Issuer)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_security.auth.appAuth.selfAuthServer.accessTokenLifespan", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vString, err := cmdFlags.GetString("security.auth.appAuth.selfAuthServer.accessTokenLifespan"); err == nil {
				assert.Equal(t, string(defaultServerConfig.Security.Auth.AppAuth.SelfAuthServer.AccessTokenLifespan.String()), vString)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := defaultServerConfig.Security.Auth.AppAuth.SelfAuthServer.AccessTokenLifespan.String()

			cmdFlags.Set("security.auth.appAuth.selfAuthServer.accessTokenLifespan", testValue)
			if vString, err := cmdFlags.GetString("security.auth.appAuth.selfAuthServer.accessTokenLifespan"); err == nil {
				testDecodeJson_ServerConfig(t, fmt.Sprintf("%v", vString), &actual.Security.Auth.AppAuth.SelfAuthServer.AccessTokenLifespan)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_security.auth.appAuth.selfAuthServer.tokenHashKeySecretName", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vString, err := cmdFlags.GetString("security.auth.appAuth.selfAuthServer.tokenHashKeySecretName"); err == nil {
				assert.Equal(t, string(defaultServerConfig.Security.Auth.AppAuth.SelfAuthServer.TokenHashKeySecretName), vString)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("security.auth.appAuth.selfAuthServer.tokenHashKeySecretName", testValue)
			if vString, err := cmdFlags.GetString("security.auth.appAuth.selfAuthServer.tokenHashKeySecretName"); err == nil {
				testDecodeJson_ServerConfig(t, fmt.Sprintf("%v", vString), &actual.Security.Auth.AppAuth.SelfAuthServer.TokenHashKeySecretName)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_security.auth.appAuth.selfAuthServer.tokenSigningRSAKeySecretName", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vString, err := cmdFlags.GetString("security.auth.appAuth.selfAuthServer.tokenSigningRSAKeySecretName"); err == nil {
				assert.Equal(t, string(defaultServerConfig.Security.Auth.AppAuth.SelfAuthServer.TokenSigningRSAKeySecretName), vString)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("security.auth.appAuth.selfAuthServer.tokenSigningRSAKeySecretName", testValue)
			if vString, err := cmdFlags.GetString("security.auth.appAuth.selfAuthServer.tokenSigningRSAKeySecretName"); err == nil {
				testDecodeJson_ServerConfig(t, fmt.Sprintf("%v", vString), &actual.Security.Auth.AppAuth.SelfAuthServer.TokenSigningRSAKeySecretName)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_security.auth.appAuth.selfAuthServer.oldTokenSigningRSAKeySecretName", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vString, err := cmdFlags.GetString("security.auth.appAuth.selfAuthServer.oldTokenSigningRSAKeySecretName"); err == nil {
				assert.Equal(t, string(defaultServerConfig.Security.Auth.AppAuth.SelfAuthServer.OldTokenSigningRSAKeySecretName), vString)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("security.auth.appAuth.selfAuthServer.oldTokenSigningRSAKeySecretName", testValue)
			if vString, err := cmdFlags.GetString("security.auth.appAuth.selfAuthServer.oldTokenSigningRSAKeySecretName"); err == nil {
				testDecodeJson_ServerConfig(t, fmt.Sprintf("%v", vString), &actual.Security.Auth.AppAuth.SelfAuthServer.OldTokenSigningRSAKeySecretName)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_security.auth.appAuth.externalAuthServer.baseUrl", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vString, err := cmdFlags.GetString("security.auth.appAuth.externalAuthServer.baseUrl"); err == nil {
				assert.Equal(t, string(defaultServerConfig.Security.Auth.AppAuth.ExternalAuthServer.BaseURL.String()), vString)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := defaultServerConfig.Security.Auth.AppAuth.ExternalAuthServer.BaseURL.String()

			cmdFlags.Set("security.auth.appAuth.externalAuthServer.baseUrl", testValue)
			if vString, err := cmdFlags.GetString("security.auth.appAuth.externalAuthServer.baseUrl"); err == nil {
				testDecodeJson_ServerConfig(t, fmt.Sprintf("%v", vString), &actual.Security.Auth.AppAuth.ExternalAuthServer.BaseURL)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_security.auth.appAuth.externalAuthServer.expectedIssuer", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vString, err := cmdFlags.GetString("security.auth.appAuth.externalAuthServer.expectedIssuer"); err == nil {
				assert.Equal(t, string(defaultServerConfig.Security.Auth.AppAuth.ExternalAuthServer.ExpectedAudience), vString)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("security.auth.appAuth.externalAuthServer.expectedIssuer", testValue)
			if vString, err := cmdFlags.GetString("security.auth.appAuth.externalAuthServer.expectedIssuer"); err == nil {
				testDecodeJson_ServerConfig(t, fmt.Sprintf("%v", vString), &actual.Security.Auth.AppAuth.ExternalAuthServer.ExpectedAudience)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_security.auditAccess", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vBool, err := cmdFlags.GetBool("security.auditAccess"); err == nil {
				assert.Equal(t, bool(defaultServerConfig.Security.AuditAccess), vBool)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("security.auditAccess", testValue)
			if vBool, err := cmdFlags.GetBool("security.auditAccess"); err == nil {
				testDecodeJson_ServerConfig(t, fmt.Sprintf("%v", vBool), &actual.Security.AuditAccess)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_security.allowCors", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vBool, err := cmdFlags.GetBool("security.allowCors"); err == nil {
				assert.Equal(t, bool(defaultServerConfig.Security.AllowCors), vBool)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("security.allowCors", testValue)
			if vBool, err := cmdFlags.GetBool("security.allowCors"); err == nil {
				testDecodeJson_ServerConfig(t, fmt.Sprintf("%v", vBool), &actual.Security.AllowCors)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_security.allowedOrigins", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vStringSlice, err := cmdFlags.GetStringSlice("security.allowedOrigins"); err == nil {
				assert.Equal(t, []string([]string{}), vStringSlice)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := join_ServerConfig("1,1", ",")

			cmdFlags.Set("security.allowedOrigins", testValue)
			if vStringSlice, err := cmdFlags.GetStringSlice("security.allowedOrigins"); err == nil {
				testDecodeSlice_ServerConfig(t, join_ServerConfig(vStringSlice, ","), &actual.Security.AllowedOrigins)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_security.allowedHeaders", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vStringSlice, err := cmdFlags.GetStringSlice("security.allowedHeaders"); err == nil {
				assert.Equal(t, []string([]string{}), vStringSlice)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := join_ServerConfig("1,1", ",")

			cmdFlags.Set("security.allowedHeaders", testValue)
			if vStringSlice, err := cmdFlags.GetStringSlice("security.allowedHeaders"); err == nil {
				testDecodeSlice_ServerConfig(t, join_ServerConfig(vStringSlice, ","), &actual.Security.AllowedHeaders)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_thirdPartyConfig.flyteClient.clientId", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vString, err := cmdFlags.GetString("thirdPartyConfig.flyteClient.clientId"); err == nil {
				assert.Equal(t, string(defaultServerConfig.ThirdPartyConfig.FlyteClientConfig.ClientID), vString)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("thirdPartyConfig.flyteClient.clientId", testValue)
			if vString, err := cmdFlags.GetString("thirdPartyConfig.flyteClient.clientId"); err == nil {
				testDecodeJson_ServerConfig(t, fmt.Sprintf("%v", vString), &actual.ThirdPartyConfig.FlyteClientConfig.ClientID)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
	t.Run("Test_thirdPartyConfig.flyteClient.redirectUri", func(t *testing.T) {
		t.Run("DefaultValue", func(t *testing.T) {
			// Test that default value is set properly
			if vString, err := cmdFlags.GetString("thirdPartyConfig.flyteClient.redirectUri"); err == nil {
				assert.Equal(t, string(defaultServerConfig.ThirdPartyConfig.FlyteClientConfig.RedirectURI), vString)
			} else {
				assert.FailNow(t, err.Error())
			}
		})

		t.Run("Override", func(t *testing.T) {
			testValue := "1"

			cmdFlags.Set("thirdPartyConfig.flyteClient.redirectUri", testValue)
			if vString, err := cmdFlags.GetString("thirdPartyConfig.flyteClient.redirectUri"); err == nil {
				testDecodeJson_ServerConfig(t, fmt.Sprintf("%v", vString), &actual.ThirdPartyConfig.FlyteClientConfig.RedirectURI)

			} else {
				assert.FailNow(t, err.Error())
			}
		})
	})
}
