name: Update Boilerplate Upgrade
on:
  workflow_dispatch:

jobs:
  trigger-boilerplate-upgrade:
    name: Upgrade Boilerplate
    uses: flyteorg/flytetools/.github/workflows/boilerplate_upgrade.yml@reuseable
    secrets:
      FLYTE_BOT_PAT: ${{ secrets.FLYTE_BOT_PAT }}