name: Flyteadmin Checks

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  setup-go:
    name: Set up Go 
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.19.10"

  lint:
    name: Lint
    uses: flyteorg/flytetools/.github/workflows/lint.yml@pin-go-version-to-1.19.10
    with:
      go-version: "1.19.10"

  tests:
    name: Unit Tests
    uses: flyteorg/flytetools/.github/workflows/tests.yml@pin-go-version-to-1.19.10
    with:
      go-version: "1.19.10"
    secrets:
      FLYTE_BOT_PAT: ${{ secrets.FLYTE_BOT_PAT }}

  docker-build:
    name: Docker Build Images
    uses: flyteorg/flytetools/.github/workflows/docker_build.yml@pin-go-version-to-1.19.10

  endtoend:
    name: End2End Test
    needs: [ docker-build ]
    uses: flyteorg/flytetools/.github/workflows/end2end.yml@pin-go-version-to-1.19.10
    with:
      priorities: "P0"
      cache_key: ${{ needs.docker-build.outputs.cache_key }}

  integration:
    name: Integration Test
    needs: [ docker-build ]
    uses: flyteorg/flytetools/.github/workflows/integration.yml@pin-go-version-to-1.19.10
    with:
      cache_key: ${{ needs.docker-build.outputs.cache_key }}
      go-version: "1.19.10"

  generate:
    name: Check Go Generate
    uses: flyteorg/flytetools/.github/workflows/go_generate.yml@pin-go-version-to-1.19.10
    with:
      go-version: "1.19.10"

  bump_version:
    name: Bump Version
    if: ${{ github.event_name != 'pull_request' }}
    needs: [ endtoend,  integration, lint, tests, generate ] # Only to ensure it can successfully build
    uses: flyteorg/flytetools/.github/workflows/bump_version.yml@master
    secrets:
      FLYTE_BOT_PAT: ${{ secrets.FLYTE_BOT_PAT }}

  goreleaser:
    name: Goreleaser
    needs: [ bump_version ] # Only to ensure it can successfully build
    uses: flyteorg/flytetools/.github/workflows/goreleaser.yml@master
    secrets:
      FLYTE_BOT_PAT: ${{ secrets.FLYTE_BOT_PAT }}

  push_docker_image:
    name: Build & Push Flyteadmin Image
    needs: [ bump_version ]
    uses: flyteorg/flytetools/.github/workflows/publish.yml@master
    with:
      version: ${{ needs.bump_version.outputs.version }}
      dockerfile: Dockerfile
      push: true
      repository: ${{ github.repository }}
    secrets:
      FLYTE_BOT_PAT: ${{ secrets.FLYTE_BOT_PAT }}
      FLYTE_BOT_USERNAME: ${{ secrets.FLYTE_BOT_USERNAME }}

  push-docker-image-flytescheduler:
    name: Build & Push Flytescheduler Image
    needs: [ bump_version ]
    uses: flyteorg/flytetools/.github/workflows/publish.yml@master
    with:
      version: ${{ needs.bump_version.outputs.version }}
      push: true
      repository: flyteorg/flytescheduler
      dockerfile: scheduler.Dockerfile
    secrets:
      FLYTE_BOT_PAT: ${{ secrets.FLYTE_BOT_PAT }}
      FLYTE_BOT_USERNAME: ${{ secrets.FLYTE_BOT_USERNAME }}

