name: Master

on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  trigger-checks:
    name: Flyteadmin
    runs-on: ubuntu-latest
    uses: flyteorg/flyteadmin/.github/workflows/checks.yml@reuseable

  trigger-bump-version:
    name: Bump Version
    runs-on: ubuntu-latest
    needs: [ trigger-checks ] # Only to ensure it can successfully build
    uses: flyteorg/flytetools/.github/workflows/bump_version.yml@reuseable
    secrets:
      FLYTE_BOT_PAT: ${{ secrets.FLYTE_BOT_PAT }}

  trigger-goreleaser:
    name: Goreleaser
    runs-on: ubuntu-latest
    needs: [ trigger-bump-version ] # Only to ensure it can successfully build
    uses: flyteorg/flytetools/.github/workflows/greleaser.yml@reuseable
    secrets:
      FLYTE_BOT_PAT: ${{ secrets.FLYTE_BOT_PAT }}

  trigger-push-docker-image:
    name: Build & Push Flyteadmin Image
    runs-on: ubuntu-latest
    needs: [ trigger-bump-version ] # Only to ensure it can successfully build
    uses: flyteorg/flytetools/.github/workflows/docker.yml@reuseable
    with:
      version: ${{ needs.bump-version.outputs.version }}
      dockerfile: Dockerfile
      push: true
    secrets:
      FLYTE_BOT_PAT: ${{ secrets.FLYTE_BOT_PAT }}
      FLYTE_BOT_USERNAME: ${{ secrets.FLYTE_BOT_USERNAME }}

  trigger-push-docker-image-flytescheduler:
    name: Build & Push Flytescheduler Image
    runs-on: ubuntu-latest
    needs: [ trigger-bump-version ] # Only to ensure it can successfully build
    uses: flyteorg/flytetools/.github/workflows/docker.yml@reuseable
    with:
      version: ${{ needs.bump-version.outputs.version }}
      push: true
      dockerfile: Dockerfile.scheduler
    secrets:
      FLYTE_BOT_PAT: ${{ secrets.FLYTE_BOT_PAT }}
      FLYTE_BOT_USERNAME: ${{ secrets.FLYTE_BOT_USERNAME }}

