name: Pull Request

on:
  pull_request

jobs:
  build-docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: load-docker-cache
        name: Load Docker Cache
        uses: actions/cache@v1
        with:
          path: /tmp/tmp/docker-images
          key: /tmp/docker-images-${{ github.event.after }}
          restore-keys: |
            /tmp/docker-images-${{ github.event.before }}
            /tmp/docker-images-${{ github.event.pull_request.base.sha }}
      - name: Prime docker cache
        run: (docker load -i /tmp/tmp/docker-images/snapshot-builder.tar || true) && (docker load -i /tmp/tmp/docker-images/snapshot.tar || true)
      - name: Build dockerfile
        run: |
          docker build -t cr.flyte.org/flyteorg/${{ github.event.repository.name }}:builder --target builder --cache-from=cr.flyte.org/flyteorg/${{ github.event.repository.name }}:builder .
          docker build -t cr.flyte.org/flyteorg/${{ github.event.repository.name }}:latest --cache-from=cr.flyte.org/flyteorg/${{ github.event.repository.name }}:builder .

      - name: Tag and cache docker image
        run:  mkdir -p /tmp/tmp/docker-images && docker save cr.flyte.org/flyteorg/${{ github.event.repository.name }}:builder -o /tmp/tmp/docker-images/snapshot-builder.tar && docker save cr.flyte.org/flyteorg/${{ github.event.repository.name }}:latest -o /tmp/tmp/docker-images/snapshot.tar

      - name: Build Flytescheduler Docker Image
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: "${{ secrets.FLYTE_BOT_USERNAME }}"
          password: "${{ secrets.FLYTE_BOT_PAT }}"
          image_name: flytescheduler
          image_tag: latest,${{ github.sha }},${{ needs.bump-version.outputs.version }}
          push_git_tag: true
          push_image_and_stages: false
          dockerfile: Dockerfile.scheduler
          registry: ghcr.io
          build_extra_args: "--compress=true"


  endtoend:
    name: End to End tests
    runs-on: ubuntu-latest
    needs: [ build-docker ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: unionai/flytectl-setup-action@v0.0.1
        name: Setup flytectl
      - id: load-docker-cache
        name: Load Docker Cache
        uses: actions/cache@v1
        with:
          path: /tmp/tmp/docker-images
          key: /tmp/docker-images-${{ github.event.after }}
      - name: Create Sandbox Cluster
        run: |
          cp /tmp/tmp/docker-images/snapshot.tar snapshot.tar
          flytectl config init
          flytectl sandbox start --source=$(pwd)
      - name: Prime docker cache
        run: |
          flytectl sandbox exec -- docker load -i /root/snapshot.tar
      - name: Upgrade Helm charts
        run:  flytectl sandbox exec -- helm upgrade flyte -n flyte --kubeconfig=/etc/rancher/k3s/k3s.yaml /flyteorg/share/flyte -f /flyteorg/share/flyte/values-sandbox.yaml --set flyteadmin.image.repository=cr.flyte.org/flyteorg/flyteadmin,flyteadmin.image.tag=latest
      - name: End2End
        env:
          KUBECONFIG: /home/runner/.flyte/k3s/k3s.yaml
        run: |
          kubectl cluster-info
          kubectl get pods -n kube-system
          echo "current-context:" $(kubectl config current-context)
          echo "environment-kubeconfig:" ${KUBECONFIG}
          make end2end_execute

  integration:
    name: Integration tests
    runs-on: ubuntu-latest
    needs: [ build-docker ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: unionai/flytectl-setup-action@v0.0.1
        name: Setup flytectl
      - id: load-docker-cache
        name: Load Docker Cache
        uses: actions/cache@v1
        with:
          path: /tmp/tmp/docker-images
          key: /tmp/docker-images-${{ github.event.after }}
      - name: Create Sandbox Cluster
        run: |
          cp /tmp/tmp/docker-images/snapshot-builder.tar snapshot.tar
          flytectl config init
          flytectl sandbox start --source=$(pwd)
      - name: Prime docker cache
        run: |
          flytectl sandbox exec -- docker load -i /root/snapshot.tar
      - name: Upgrade Helm charts
        run:  flytectl sandbox exec -- helm upgrade flyte -n flyte --kubeconfig=/etc/rancher/k3s/k3s.yaml /flyteorg/share/flyte -f /flyteorg/share/flyte/values-sandbox.yaml --set flyteadmin.image.repository=cr.flyte.org/flyteorg/flyteadmin,flyteadmin.image.tag=builder
      - name: Integration
        env:
          KUBECONFIG: /home/runner/.flyte/k3s/k3s.yaml
        run: |
          # attempt to clean up some unneeded data: https://github.com/actions/virtual-environments/issues/2840#issuecomment-790492173
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          kubectl cluster-info
          kubectl get pods -n kube-system
          echo "current-context:" $(kubectl config current-context)
          echo "environment-kubeconfig:" ${KUBECONFIG}
          make k8s_integration_execute

  tests-lint:
    name: Run tests and lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Unit Tests
        uses: cedrickring/golang-action@1.7.0
        env:
          GO111MODULE: "on"
        with:
          args: make install && make test_unit_codecov
      - name: Push CodeCov
        uses: codecov/codecov-action@v1
        with:
          file: coverage.txt
          flags: unittests
          fail_ci_if_error: true
      - name: Lint
        uses: cedrickring/golang-action@1.7.0
        env:
          GO111MODULE: "on"
        with:
          args: make install && make lint
