name: Upgrade Automation
on:
  push:
    branches:
      - reuseable
  workflow_dispatch:
    inputs:
      component:
        description: "Name of Flyte component"
        required: true
        default: "boilerplate"
        type: choice
        options:
          - boilerplate
          - flyteidl
jobs:
  trigger-flyteidl-upgrade:
    name: ${{ inputs.component }} Upgrade
    uses: flyteorg/flytetools/.github/workflows/flyte_automation.yml@reuseable
    with:
      component: ${{ inputs.component }}
    secrets:
      FLYTE_BOT_PAT: ${{ secrets.FLYTE_BOT_PAT }}
